name: Electron CI/CD

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Use Node.js 20 LTS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Clear pnpm cache
        run: pnpm store prune

      - name: Install dependencies
        run: NODE_OPTIONS="--max-old-space-size=8192" pnpm install

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Build
        run: pnpm build:mac

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: dist-${{ matrix.os }}
          path: dist/

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-macos-latest
          path: release-artifacts

      - name: Generate Changelog
        uses: mikepenz/release-changelog-generator@v1
        id: changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fromTag: ${{ github.event.repository.default_branch }}
          toTag: ${{ github.ref }}
          outputFile: CHANGELOG.md

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-artifacts/**/*
          draft: false
          token: ${{ secrets.GH_TOKEN }}
          body_path: CHANGELOG.md
